#!/bin/sh
set -eu

project_name=$1
java_home=${JAVA_HOME:-/opt/java/openjdk}

mkdir -p /workspace/project /output
cp -a /input/. /workspace/project/
project=/workspace/project/$project_name

/opt/mendix/modeler/mxbuild \
  "--java-home=$java_home" \
  "--java-exe-path=$java_home/bin/java" \
  --target=portable-app-package \
  --output=/output/runtime.zip \
  "$project"
