# frozen_string_literal: true

require 'fileutils'
require 'json'

module Mxrb
  module Model
    # Materializes the typed design-system contract into MXRB-owned theme files.
    class DesignMaterializer
      IMPORT = '@import "mxrb-design-system";'

      def initialize(root, definition)
        @root = File.expand_path(root)
        @definition = definition
      end

      def materialize!
        tokens = valued_tokens(@definition.fetch(:tokens, []))
        themes = resolved_themes
        return self if tokens.empty? && themes.empty?

        write(File.join('theme', 'web', '_mxrb-design-system.scss'), stylesheet(tokens, themes))
        ensure_import
        write(
          File.join('themesource', 'mxrb', 'web', 'design-properties.json'),
          JSON.pretty_generate(design_properties(tokens)) << "\n"
        )
        self
      end

      private

      def valued_tokens(tokens) = Array(tokens).reject { _1[:value].nil? }

      def resolved_themes
        themes = Array(@definition[:themes]).to_h { [_1.fetch(:name).to_s, _1] }
        themes.keys.sort.map { [_1, resolve_theme(_1, themes, [])] }
      end

      def resolve_theme(name, themes, trail)
        return [] unless themes.key?(name)
        raise SerializationError, "design-system theme inheritance cycle: #{(trail + [name]).join(' -> ')}" \
          if trail.include?(name)

        theme = themes.fetch(name)
        inherited = theme[:inherits] ? resolve_theme(theme[:inherits].to_s, themes, trail + [name]) : []
        merge_tokens(inherited, valued_tokens(theme.fetch(:tokens, [])))
      end

      def merge_tokens(inherited, own) = (inherited + own).reverse.uniq { token_property(_1) }.reverse

      def stylesheet(tokens, themes)
        sections = []
        sections << css_block(':root', tokens) unless tokens.empty?
        themes.reject { _2.empty? }.each do |name, theme_tokens|
          slug = slug(name)
          sections << css_block(
            %(:root[data-mxrb-theme="#{slug}"], .mxrb-theme-#{slug}),
            theme_tokens
          )
        end
        "/* Generated by MXRB from the Ruby design_system contract. */\n#{sections.join("\n\n")}\n"
      end

      def css_block(selector, tokens)
        declarations = tokens.map do |token|
          "  #{token_property(token)}: #{safe_value(token.fetch(:value))};"
        end
        "#{selector} {\n#{declarations.join("\n")}\n}"
      end

      def token_property(token)
        name = token.fetch(:name).to_s
        return name if name.match?(/\A--[a-zA-Z0-9_-]+\z/)
        return "--#{slug(name.delete_prefix('$'))}" if name.start_with?('$')

        "--#{slug(token.fetch(:kind))}-#{slug(name)}"
      end

      def safe_value(value)
        text = value.to_s.strip
        raise SerializationError, "unsafe design-system token value: #{value.inspect}" \
          if text.empty? || text.match?(/[\n\r;{}]/)

        text
      end

      def slug(value)
        result = value.to_s.gsub(/([a-z\d])([A-Z])/, '\1-\2')
                      .downcase.gsub(/[^a-z0-9_-]+/, '-').gsub(/\A-+|-+\z/, '')
        raise SerializationError, "invalid design-system name: #{value.inspect}" if result.empty?

        result
      end

      def design_properties(tokens)
        colors = tokens.select { _1.fetch(:kind).to_sym == :color }.map do |token|
          {
            'category' => 'MXRB design system',
            'name' => human_name(token.fetch(:name)),
            'type' => 'ColorPicker',
            'property' => token_property(token)
          }
        end
        { 'Widget' => colors }
      end

      def human_name(name) = slug(name.to_s.delete_prefix('$').delete_prefix('--'))
        .split('-').map(&:capitalize).join(' ')

      def ensure_import
        path = File.join(@root, 'theme', 'web', 'main.scss')
        current = File.file?(path) ? File.binread(path) : ''
        return if current.lines.map(&:strip).include?(IMPORT)

        separator = current.empty? || current.end_with?("\n") ? '' : "\n"
        write(File.join('theme', 'web', 'main.scss'), "#{current}#{separator}#{IMPORT}\n")
      end

      def write(relative, contents)
        target = File.join(@root, relative)
        temporary = "#{target}.mxrb-#{Process.pid}"
        begin
          FileUtils.mkdir_p(File.dirname(target))
          File.binwrite(temporary, contents)
          FileUtils.mv(temporary, target)
        ensure
          FileUtils.rm_f(temporary)
        end
      end
    end
  end
end
